### ISSUE TITLE
[Feat] 회원가입시 생일선택 이슈 & 시스템 설정기능 추가 & 지도이슈 수정

### ISSUE THREAD

**Issue by JoStar33** [Central-MakeUs/OpenOff-Client#106]
### - 구현할 기능
- 각종 이슈와 기능들을 구현해야합니다.

### - 해당 기능을 만들기 위해 수행할 작업

- 회원가입시 생일선택이 정상적으로 이루어지지 않는 이슈를 수정해야 합니다. 
- 시스템 설정기능을 추가해야 합니다. 
- 현지도에서 위치검색 버튼이 처음 열릴때 깜빡거리는 이슈를 수정해야 합니다.
- 지도 달력을 선택하고 들어올때 API가 두번 호출되는 이슈를 수정해야 합니다.
- FCM 토큰을 서버에 보내는 방식을 개선합니다.
- 로그아웃시 리액트 쿼리가 모두 초기화되어야 합니다.

### - 예상 소요 시간

1day

**Comment by yeonju0110** [comment]
혹시 이 이슈에서 네이버, 구글 로그인 아이콘 막아줄 수 있나요?.? @JoStar33

**Comment by JoStar33** [comment]
@yeonju0110 오 넵 같이 막아버릴게요~!
