### ISSUE TITLE
[Bug] IOS 퍼블리싱 화면 버그

### ISSUE THREAD

**Issue by JoStar33** [Central-MakeUs/OpenOff-Client#31]
### - 오류명

IOS의 화면이 제대로 적용되지않는 버그가 있습니다.  이를 바로잡아야 합니다.

### - OS Type
- [ ]  window
- [x]  ios
- [ ]  android
- [ ]  web

### - 해당 버그를 해결하기 위한 방법에 있다면 자유롭게 작성해주세요.

- 버그 해결을 위해 react-native-expo 환경을 조성하고, 조성한 환경에서 IOS화면을 확인해야합니다.(현재까지 nmaps를 제외하고 정상동작함을 확인했습니다.)
- IOS 환경에서도 안드로이드처럼 버튼이 키보드위로 올라와야합니다. 이를 구현해야합니다.
- 중앙정렬을 위해 margin 혹은 top & bottom을 적용한 값들이 정상적으로 적용되고있지 않습니다. 이를 추적하여 수정해야합니다.

**Comment by JoStar33** [comment]
심각한 이슈이므로 다른 이슈들을 후순위로 두고 개발 진행하겠습니다.

**Comment by yeonju0110** [comment]
죠스타 화이팅...,, 👍🏻
